# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160706080347 on 2016-07-26 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
